### ISSUE TITLE
Add link to Segger's MMD chapter of it's J-link user Guide

### ISSUE THREAD

**Issue by haakonsh** [NordicPlayground/j-link-monitoring-mode-debugging#2]
https://www.segger.com/downloads/jlink/UM08001 Chapter 9.

**Comment by awneil** [comment]
A translation of Segger's generic description to Nordic's specific terminology would help.

eg, Segger refer to, _"an additional software layer that takes all interrupts in the first place and forwards them to the user application"_ - it would be good to explain that this is the SoftDevice in nRF52 applications. (I presume?)

**Comment by haakonsh** [comment]
I agree, and I'll add it :)
